# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

target 'VK_app' do
  pod 'Alamofire', '~> 4.9.0'
  pod 'SwiftyJSON', '~>5.0.0'
  pod 'Kingfisher', '~> 5.7.1'
  pod 'RealmSwift', '~> 3.17.3'
  pod 'SwiftKeychainWrapper', '~> 3.4.0'
  pod 'PromiseKit', '~> 6.8'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'SnapKit', '~> 5.0.1'

end
